config-version: 2
version: 2
sources:
  - name: hubspot
    database: pc_fivetran_db
    schema: hubspot

    tables:
      - name: contact 
      - name: deal
      - name: ticket 
      - name: deal_contact
    
  - name: bubble
    database: source_bubble
    schema: bubble_app_tables

    tables:
      - name: availability  
      - name: dependent
      - name: insurance
      - name: parent
      - name: parent_insurance
      - name: provider
      - name: provider_education
      - name: provider_tag 
      - name: session
      - name: session_provider 
      - name: session_type 
      - name: temp_busy_slot 
      - name: user 
      - name: busy_slot
  
  - name: claims
    database: source_claims
    schema: uploaded_claims 

    tables: 
      - name: monthly_claims_upload 
    
  - name: google_sheets
    database: pc_fivetran_db
    schema: google_sheets

    tables: 
    - name: evaluation_outcome
    - name: session_outcome 