config-version: 2
version: 2
sources:
  - name: hubspot
    database: pc_fivetran_db
    schema: hubspot

    tables:
      - name: contact 
      - name: deal

  - name: csv_uploads
    database: csv_uploads
    schema: public
    
    tables:
      - name: LAT_LNG_ZIP_TABLE 
    

