with source as (
        select * from {{ source('hubspot', 'ticket') }}
  ),
  renamed as (
      SELECT 
    -- Basic identifiers
    {{ adapter.quote("ID") }} AS ticket_id,
    {{ adapter.quote("PROPERTY_HS_OBJECT_ID") }} AS hubspot_object_id,
    {{ adapter.quote("PROPERTY_HS_TICKET_ID") }} AS ticket_number,
    
    -- Question 1: Generated by Coral Care vs. inbound
    {{ adapter.quote("PROPERTY_HS_LAST_EMAIL_TYPE") }} AS last_email_type,
    {{ adapter.quote("PROPERTY_HS_OUTBOUND_TICKET") }} AS is_outbound_ticket,
    {{ adapter.quote("PROPERTY_HS_OBJECT_SOURCE") }} AS object_source,
    {{ adapter.quote("PROPERTY_HS_OBJECT_SOURCE_LABEL") }} AS object_source_label,
    
    -- Question 2: Urgency  
    {{ adapter.quote("PROPERTY_HS_TICKET_PRIORITY") }} AS ticket_priority,
    
    -- Question 4: Subject Line
    {{ adapter.quote("PROPERTY_SUBJECT") }} AS subject_line,
    {{ adapter.quote("PROPERTY_HS_EMAIL_SUBJECT") }} AS email_subject,
    
    -- Question 6 & 8: Time to first response
    {{ adapter.quote("PROPERTY_HS_TIME_TO_FIRST_RESPONSE_SLA_STATUS") }} AS first_response_sla_status,
    {{ adapter.quote("PROPERTY_HS_TIME_TO_FIRST_RESPONSE_IN_OPERATING_HOURS") }} AS time_to_first_response_hours,
    {{ adapter.quote("PROPERTY_HS_TIME_TO_FIRST_RESPONSE_SLA_AT") }} AS first_response_sla_timestamp,
    {{ adapter.quote("PROPERTY_TIME_TO_FIRST_AGENT_REPLY") }} AS time_to_first_agent_reply,
    {{ adapter.quote("PROPERTY_FIRST_AGENT_REPLY_DATE") }} AS first_agent_reply_date,
    
    -- Question 7: Coral Care member who took care of ticket
    {{ adapter.quote("PROPERTY_HUBSPOT_OWNER_ID") }} AS owner_id,
    {{ adapter.quote("PROPERTY_HUBSPOT_TEAM_ID") }} AS team_id,
    {{ adapter.quote("PROPERTY_HS_ASSIGNED_TEAM_IDS") }} AS assigned_team_ids,
    {{ adapter.quote("PROPERTY_HUBSPOT_OWNER_ASSIGNEDDATE") }} AS owner_assigned_date,
    
    -- Question 9: Time to ticket close
    {{ adapter.quote("PROPERTY_TIME_TO_CLOSE") }} AS time_to_close,
    {{ adapter.quote("PROPERTY_HS_TIME_TO_CLOSE_IN_OPERATING_HOURS") }} AS time_to_close_hours,
    {{ adapter.quote("PROPERTY_HS_TIME_TO_CLOSE_SLA_AT") }} AS close_sla_timestamp,
    {{ adapter.quote("PROPERTY_CLOSED_DATE") }} AS closed_date,
    {{ adapter.quote("PROPERTY_HS_LAST_CLOSED_DATE") }} AS last_closed_date,
    
    -- Question 10: SLA status
    {{ adapter.quote("PROPERTY_HS_TIME_TO_FIRST_RESPONSE_SLA_STATUS") }} AS first_response_sla,
    {{ adapter.quote("PROPERTY_HS_TIME_TO_CLOSE_SLA_STATUS") }} AS close_sla_status,
    {{ adapter.quote("PROPERTY_HS_TIME_TO_NEXT_RESPONSE_SLA_STATUS") }} AS next_response_sla_status,
    {{ adapter.quote("PROPERTY_HS_APPLIED_SLA_RULE_CONFIG_ID") }} AS sla_rule_config_id,
    {{ adapter.quote("PROPERTY_HS_APPLIED_SLA_SCHEDULE_ID") }} AS sla_schedule_id,
    
    -- Question 11: Support vs. Provider Pipeline
    {{ adapter.quote("PROPERTY_HS_PIPELINE") }} AS pipeline,
    {{ adapter.quote("PROPERTY_HS_PIPELINE_STAGE") }} AS pipeline_stage,
    
    -- Additional useful fields
    {{ adapter.quote("PROPERTY_HS_TICKET_CATEGORY") }} AS ticket_category,
    {{ adapter.quote("PROPERTY_HS_IN_HELPDESK") }} AS in_helpdesk,
    {{ adapter.quote("PROPERTY_HS_IS_VISIBLE_IN_HELP_DESK") }} AS visible_in_help_desk,
    {{ adapter.quote("PROPERTY_HS_NUM_ASSOCIATED_CONVERSATIONS") }} AS num_conversations,
    {{ adapter.quote("PROPERTY_HS_NUM_ASSOCIATED_COMPANIES") }} AS num_companies,
    {{ adapter.quote("PROPERTY_HS_PRIMARY_COMPANY_ID") }} AS primary_company_id,
    {{ adapter.quote("PROPERTY_HS_PRIMARY_COMPANY_NAME") }} AS primary_company_name,
    
    -- Timestamps
    {{ adapter.quote("PROPERTY_CREATEDATE") }} AS created_date,
    {{ adapter.quote("PROPERTY_HS_LASTMODIFIEDDATE") }} AS last_modified_date,
    {{ adapter.quote("PROPERTY_HS_LASTACTIVITYDATE") }} AS last_activity_date,
    {{ adapter.quote("PROPERTY_HS_LASTCONTACTED") }} AS last_contacted_date,
    
    -- Content and notes
    {{ adapter.quote("PROPERTY_CONTENT") }} AS ticket_content,
    {{ adapter.quote("PROPERTY_NUM_NOTES") }} AS num_notes,
    {{ adapter.quote("PROPERTY_HS_NUM_TIMES_CONTACTED") }} AS num_times_contacted,
    
    -- Assignment and routing
    {{ adapter.quote("PROPERTY_HS_ASSIGNMENT_METHOD") }} AS assignment_method,
    {{ adapter.quote("PROPERTY_CREATED_BY") }} AS created_by,
    
    -- Email tracking
    {{ adapter.quote("PROPERTY_HS_LAST_EMAIL_DATE") }} AS last_email_date,
    {{ adapter.quote("PROPERTY_HS_LAST_EMAIL_ID") }} AS last_email_id,
    {{ adapter.quote("PROPERTY_HS_SALES_EMAIL_LAST_REPLIED") }} AS sales_email_last_replied,
    
    -- Fivetran metadata
    {{ adapter.quote("_FIVETRAN_SYNCED") }} AS fivetran_synced,
    {{ adapter.quote("_FIVETRAN_DELETED") }} AS is_deleted
    
  FROM source 
  WHERE {{ adapter.quote("_FIVETRAN_DELETED") }} = FALSE
  )
  select * from renamed
    