
SELECT
    session_id,
    Patient_Name,
    SPLIT_PART(Patient_Name, ' ', 1) as dependent_first_name,
    SPLIT_PART(Patient_Name, ' ', -1) as dependent_last_name,
    Patient_ID,
    Payer_Name,
    Date_Of_Service,
    Year_Month,
    Place_of_Service_Code, 
    Service_Type,
    Category,
    Claim_Status,
    Claim_Category,
    Charges,
    CPT_Code1,
    Code_1_Charge,
    CPT_Code2,
    Code2_Charge,
    CPT_code3,
    Code_3_Charge,
    CPT_code_4,
    Code_4_Charge,
    CPT_Code_X_Number_of_units,
    Payer_Claim_No as Payer_Claim_Number,
    Processed_Denied_Date,
    Allowed_Amount,
    Paid_Amount,
    Copay,
    Coins,
    Deductible,
    Total_PTR,
    Check_EFT_Number,
    Check_EFT,
    EFT_Amount,
    EFT_Date,
    Comment,
    Status,
    Total_Insurance_Projection,
    Total_Rev_Projection,
    Session_Type,
    Total_Allowable,
    Total_Collected,
    Total_Code_Charge,
    Paid_Status,
    Insurer_Code_Combo,
    Insurer_Code_Lookup,
    Charge_Code_1,
    Charge_Code_1_Code,
    Charge_Code_2,
    Charge_Code_2_Code,
    Charge_Code_3,
    Charge_Code_3_Code,
    Charge_Code_4,
    Charge_Code_4_Code,
    Hold_1
from {{ source('claims', 'monthly_claims_upload') }}