with source as (
        select * from {{ source('hubspot', 'engagement_call') }}
  ),
  renamed as (
      select
          {{ adapter.quote("ENGAGEMENT_ID") }},
        {{ adapter.quote("TYPE") }},
        {{ adapter.quote("_FIVETRAN_DELETED") }},
        {{ adapter.quote("_FIVETRAN_SYNCED") }},
        {{ adapter.quote("PROPERTY_HS_CALL_STATUS") }},
        {{ adapter.quote("PROPERTY_HS_CONNECTED_COUNT") }},
        {{ adapter.quote("PROPERTY_HUBSPOT_TEAM_ID") }},
        {{ adapter.quote("PROPERTY_HS_ALL_ACCESSIBLE_TEAM_IDS") }},
        {{ adapter.quote("PROPERTY_HS_ENGAGEMENT_SOURCE_ID") }},
        {{ adapter.quote("PROPERTY_HS_VOICEMAIL_COUNT") }},
        {{ adapter.quote("PROPERTY_HS_LASTMODIFIEDDATE") }},
        {{ adapter.quote("PROPERTY_HS_CALL_EXTERNAL_ID") }},
        {{ adapter.quote("PROPERTY_HS_CALL_TO_NUMBER_NICKNAME") }},
        {{ adapter.quote("PROPERTY_HS_CREATEDATE") }},
        {{ adapter.quote("PROPERTY_HS_OBJECT_SOURCE") }},
        {{ adapter.quote("PROPERTY_HS_CALL_TO_NUMBER") }},
        {{ adapter.quote("PROPERTY_HS_UNIQUE_ID") }},
        {{ adapter.quote("PROPERTY_HS_CALL_DURATION") }},
        {{ adapter.quote("PROPERTY_HS_CALLS_SERVICE_CALL_ID") }},
        {{ adapter.quote("PROPERTY_HS_CALL_DIRECTION") }},
        {{ adapter.quote("PROPERTY_HS_ENGAGEMENT_SOURCE") }},
        {{ adapter.quote("PROPERTY_HS_CALL_TITLE") }},
        {{ adapter.quote("PROPERTY_HUBSPOT_OWNER_ASSIGNEDDATE") }},
        {{ adapter.quote("PROPERTY_HS_OBJECT_SOURCE_ID") }},
        {{ adapter.quote("PROPERTY_HS_ALL_TEAM_IDS") }},
        {{ adapter.quote("PROPERTY_HS_CALL_FROM_NUMBER") }},
        {{ adapter.quote("PROPERTY_HS_CREATED_BY") }},
        {{ adapter.quote("PROPERTY_HS_OBJECT_SOURCE_LABEL") }},
        {{ adapter.quote("PROPERTY_HUBSPOT_OWNER_ID") }},
        {{ adapter.quote("PROPERTY_HS_TIMESTAMP") }},
        {{ adapter.quote("PROPERTY_HS_CALL_EXTERNAL_ACCOUNT_ID") }},
        {{ adapter.quote("PROPERTY_HS_CALL_HAS_VOICEMAIL") }},
        {{ adapter.quote("PROPERTY_HS_CALL_SOURCE") }},
        {{ adapter.quote("PROPERTY_HS_OBJECT_ID") }},
        {{ adapter.quote("PROPERTY_HS_ENGAGEMENTS_LAST_CONTACTED") }},
        {{ adapter.quote("PROPERTY_HS_USER_IDS_OF_ALL_OWNERS") }},
        {{ adapter.quote("PROPERTY_HS_ALL_OWNER_IDS") }},
        {{ adapter.quote("PROPERTY_HS_CALL_DEAL_STAGE_DURING_CALL") }},
        {{ adapter.quote("PROPERTY_HS_CALL_CALLEE_OBJECT_ID") }},
        {{ adapter.quote("PROPERTY_HS_UPDATED_BY_USER_ID") }},
        {{ adapter.quote("PROPERTY_HS_CREATED_BY_USER_ID") }},
        {{ adapter.quote("PROPERTY_HS_CALL_CALLEE_OBJECT_TYPE") }},
        {{ adapter.quote("PROPERTY_HS_CALL_FROM_NUMBER_NICKNAME") }},
        {{ adapter.quote("PROPERTY_HS_MODIFIED_BY") }},
        {{ adapter.quote("PROPERTY_HS_OBJECT_SOURCE_USER_ID") }},
        {{ adapter.quote("PROPERTY_HS_CALL_BODY") }},
        {{ adapter.quote("PROPERTY_HS_BODY_PREVIEW_IS_TRUNCATED") }},
        {{ adapter.quote("PROPERTY_HS_BODY_PREVIEW_HTML") }},
        {{ adapter.quote("PROPERTY_HS_BODY_PREVIEW") }},
        {{ adapter.quote("PROPERTY_HS_CALL_DISPOSITION") }},
        {{ adapter.quote("PROPERTY_HS_ACTIVITY_TYPE") }},
        {{ adapter.quote("PROPERTY_HS_AT_MENTIONED_OWNER_IDS") }},
        {{ adapter.quote("PROPERTY_HS_CALL_TRANSCRIPT_AUDIO_NUM_CHANNELS") }},
        {{ adapter.quote("PROPERTY_HS_CALL_HAS_TRANSCRIPT") }},
        {{ adapter.quote("PROPERTY_HS_CALL_RECORDING_URL") }},
        {{ adapter.quote("PROPERTY_HS_CALL_LOCATION") }},
        {{ adapter.quote("PROPERTY_HS_CALL_PHONE_NUMBER_SOURCE") }},
        {{ adapter.quote("PROPERTY_HS_CALL_UNIFIED_PHONE_NUMBER_ID") }},
        {{ adapter.quote("PROPERTY_HS_CALL_ROUTING_STRATEGY_TYPE") }},
        {{ adapter.quote("PROPERTY_HS_OBJECT_SOURCE_DETAIL_1") }},
        {{ adapter.quote("PROPERTY_HS_CALL_APP_ID") }},
        {{ adapter.quote("PROPERTY_HS_CALL_MEETING_ID") }},
        {{ adapter.quote("PROPERTY_HS_CALL_ZOOM_MEETING_UUID") }},
        {{ adapter.quote("PROPERTY_HS_CALL_UNIQUE_EXTERNAL_ID") }},
        {{ adapter.quote("PROPERTY_HS_HOSTED_VIDEO_CONFERENCE_URL") }}

      from source
  )
  select * from renamed
    