SELECT 
 parent.parent_email,
parent.coral_parent_id,
parent.parent_first_name,
parent.parent_last_name,
parent.parent_address AS street_address,
parent.parent_location_lat AS latitude, 
parent.parent_location_lng AS longitude,
parent.parent_city,
parent.parent_state AS state_region_code,
parent.parent_postal_code,
parent.parent_phone,
session_parent.most_recent_provider_type AS Provider_Type,
session_parent.first_session_frequency AS appointment_frequency,
session_parent.most_recent_appt_type,
session_parent.upcoming_appt_type, 
session_parent.session_count,
/*added dependent fields here */
session_parent.payment_type AS type_of_payment,
parent.insurance_providers,
parent.parent_last_login_date,
parent.parent_first_login_date,
session_parent.upcoming_session_date,
session_parent.upcoming_session_time,
session_parent.farthest_out_session_date,
session_parent.first_session_date,
session_parent.most_recent_session_date,
session_parent.first_session_frequency,
session_parent.reason_for_visit,
session_parent.payment_type,
session_parent.coral_care_status,
session_parent.most_recent_provider_name,
session_parent.upcoming_provider_name,

session_parent.dependent_1_name,
session_parent.dependent_1_first_name,
session_parent.dependent_1_last_name,
session_parent.dependent_1_dob,
session_parent.dependent_1_age_number,
session_parent.dependent_1_age_unit,
session_parent.dependent_1_gender,
session_parent.dependent_1_reason_for_visit,
    
session_parent.dependent_2_name,
session_parent.dependent_2_first_name,
session_parent.dependent_2_last_name,
session_parent.dependent_2_dob,
session_parent.dependent_2_age_number,
session_parent.dependent_2_age_unit,
session_parent.dependent_2_gender,
session_parent.dependent_2_reason_for_visit
    
-- session_parent.dependent_3_name,
-- session_parent.dependent_3_first_name,
-- session_parent.dependent_3_last_name,
-- session_parent.dependent_3_dob,
-- session_parent.dependent_3_age_number,
-- session_parent.dependent_3_age_unit,
-- session_parent.dependent_3_gender,
-- session_parent.dependent_3_reason_for_visit
FROM {{ref('int__parent')}} AS parent
LEFT JOIN {{ref('int__session_parent')}} AS session_parent
ON parent.coral_parent_id = session_parent.coral_parent_id
WHERE parent.bubble_parent_user_id is not null